### ISSUE TITLE
[contract][cs-5.20]: Lack of Adherence to Solidity Coding Conventions and Insufficient Documentation

### ISSUE THREAD

**Issue by byteflyfunny** [mantlenetworkio/mantle#1092] opened 2023-06-23 11:35 UTC
The Solidity code of the in-scope smart contracts does not follow the standard [Solidity naming conventions](https://docs.soliditylang.org/en/v0.8.17/style-guide.html). It contains several internal and private functions not prefixed with an underscore, making it difficult to determine their visibility level.

**Comment by afkbyte** [comment] 2023-06-23 20:11
duplicate of #1071

**Closed** 2023-06-27 09:24 UTC
