### ISSUE TITLE
[contract][cs-5.18]: Use .call() Instead of .transfer() in Payment functions

### ISSUE THREAD

**Issue by byteflyfunny** [mantlenetworkio/mantle#1098] opened 2023-06-23 15:50 UTC
TssRewardContract

`addr.transfer(sendAmount);`
`payable(owner()).transfer(dust);`

**Comment by afkbyte** [comment] 2023-06-23 20:09
duplicate of #1070

**Closed** 2023-06-27 09:22 UTC
